### ISSUE TITLE
sgload run failed with read: connection reset by peer

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/sgload#11]
http://uberjenkins.sc.couchbase.com/view/Performance/job/sync-gateway-perf-test/31/consoleFull

```
10:51:00 t=2016-10-14T10:43:17-0700 lvl=info msg="Wait until writers finish"
10:51:00 t=2016-10-14T10:43:59-0700 lvl=warn msg="Document missing created_at field" doc.Body="map[reason:Invalid doc/rev ID in _bulk_get status:400 error:bad_request id:]"
10:51:00 t=2016-10-14T10:43:59-0700 lvl=warn msg="Document missing created_at field" doc.Body="map[error:bad_request id: reason:Invalid doc/rev ID in _bulk_get status:400]"
10:51:00 t=2016-10-14T10:43:59-0700 lvl=warn msg="Document missing created_at field" doc.Body="map[error:bad_request id: reason:Invalid doc/rev ID in _bulk_get status:400]"
10:51:00 t=2016-10-14T10:44:00-0700 lvl=warn msg="Document missing created_at field" doc.Body="map[error:bad_request id: reason:Invalid doc/rev ID in _bulk_get status:400]"
10:51:00 t=2016-10-14T10:44:00-0700 lvl=warn msg="Document missing created_at field" doc.Body="map[error:bad_request id: reason:Invalid doc/rev ID in _bulk_get status:400]"
10:51:00 t=2016-10-14T10:44:01-0700 lvl=warn msg="Document missing created_at field" doc.Body="map[error:bad_request id: reason:Invalid doc/rev ID in _bulk_get status:400]"
10:51:00 
10:51:00 2016/10/14 10:43:16 glNumReaders: 100
10:51:00 panic: Error performing update: Post http://s61705cnt72.sc.couchbase.com:4984/db/_bulk_docs: read tcp 172.23.108.88:19154->172.23.108.83:4984: read: connection reset by peer
10:51:00 
10:51:00 goroutine 857 [running]:
10:51:00 github.com/couchbaselabs/sgload/sgload.(*Updater).Run(0xc82007c090)
10:51:00    /opt/go/src/github.com/couchbaselabs/sgload/sgload/updater.go:89 +0xa86
10:51:00 created by github.com/couchbaselabs/sgload/sgload.GateLoadRunner.startUpdaters
10:51:00    /opt/go/src/github.com/couchbaselabs/sgload/sgload/gateload_runner.go:161 +0x3e4
```

**Comment by tleyden** [comment]
I ssh'd into the load generator vm and ran:

```
sgload gateload --createreaders --createwriters --numreaders 25 --numupdaters 25 --numwriters 25 --numrevsperdoc 10 --numdocs 5000 --numchannels 10 --statsdendpoint localhost:8125 --statsdenabled --sg-url http://s61705cnt72.sc.couchbase.com:4984/db/
```

I'm not seeing the same sgload panic yet, but on the sync gateway index reader I see these logs:

```
2016-10-14T11:14:52.641-07:00 WARNING: Error unmarshalling entry for key _idx_entry:56:36: unexpected end of JSON input -- db.(*BitFlagStorage).bulkLoadEntries() at kv_channel_storage.go:432
2016-10-14T11:14:52.641-07:00 WARNING: Error unmarshalling entry for key _idx_entry:56:35: unexpected end of JSON input -- db.(*BitFlagStorage).bulkLoadEntries() at kv_channel_storage.go:432
2016-10-14T11:14:52.641-07:00 WARNING: Error unmarshalling entry for key _idx_entry:56:33: unexpected end of JSON input -- db.(*BitFlagStorage).bulkLoadEntries() at kv_channel_storage.go:432
2016-10-14T11:14:52.641-07:00 WARNING: Error unmarshalling entry for key _idx_entry:56:32: unexpected end of JSON input -- db.(*BitFlagStorage).bulkLoadEntries() at kv_channel_storage.go:432
2016-10-14T11:14:52.641-07:00 WARNING: Error unmarshalling entry for key _idx_entry:56:28: unexpected end of JSON input -- db.(*BitFlagStorage).bulkLoadEntries() at kv_channel_storage.go:432
```

and in sgload logs, I see:

```
WARN[10-14|11:17:39] Document missing created_at field        doc.Body="map[status:400 error:bad_request id: reason:Invalid doc/rev ID in _bulk_get]"
WARN[10-14|11:17:40] Document missing created_at field        doc.Body="map[status:400 error:bad_request id: reason:Invalid doc/rev ID in _bulk_get]"
WARN[10-14|11:17:40] Document missing created_at field        doc.Body="map[error:bad_request id: reason:Invalid doc/rev ID in _bulk_get status:400]"
WARN[10-14|11:17:46] Document missing created_at field        doc.Body="map[error:bad_request id: reason:Invalid doc/rev ID in _bulk_get status:400]"
WARN[10-14|11:17:50] Document missing created_at field        doc.Body="map[id: reason:Invalid doc/rev ID in _bulk_get status:400 error:bad_request]"
```

**Comment by tleyden** [comment]
Re-running again but not seeing the same errors this time, but am seeing slow times (12s) writing to the bucket:

```
_time=2016-10-14T14:06:48.663-07:00 _level=INFO _msg=go-couchbase: call to Do("_sync:rev:3960-70a93fcc-a218-46e1-aaea-fa74831601f1:34:5-fc3a81d63c21491623fb1ebab9809c44") in github.com/couchbase/go-couchbase.(*Bucket).Write took 12.066169676s
```

**Comment by tleyden** [comment]
> Re-running again but not seeing the same errors this time, but am seeing slow times (12s) writing to the bucket:

Nevermind, it took a few minutes.  Able to reproduce again.

**Comment by tleyden** [comment]
I think this might have been due to excessive [TIME WAIT sockets](http://tleyden.github.io/blog/2016/11/21/tuning-the-go-http-client-library-for-load-testing/), closing as fixed.
