### ISSUE TITLE
Unexpected high roundtrip time

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/sgload#12]
In http://uberjenkins.sc.couchbase.com/view/Performance/job/sync-gateway-perf-test/44/, seeing unexpected high round trip times of several minutes.

Not sure if this is an sgload bug or what, but I'm looking into it

**Comment by tleyden** [comment]
While trying to debug this, noticing other failures like http://uberjenkins.sc.couchbase.com/view/Performance/job/sync-gateway-perf-test/52/console where it's failing with:

```
5:09:55 t=2016-10-17T15:09:24-0700 lvl=info msg="Wait until updaters finish"
15:09:55 t=2016-10-17T15:09:55-0700 lvl=eror msg="Error calling pullMoreDocs" agent.ID=0 since= err="RetryLoop for pullMoreDocs giving up after 8 attempts"
15:09:55 t=2016-10-17T15:09:55-0700 lvl=info msg="Reader finished" agent.ID=0 numdocs=0
15:09:55 
15:09:55 2016/10/17 15:08:49 glNumReaders: 10
15:09:55 panic: Error calling pullMoreDoc: RetryLoop for pullMoreDocs giving up after 8 attempts
15:09:55 
15:09:55 goroutine 19 [running]:
15:09:55 github.com/couchbaselabs/sgload/sgload.(*Reader).Run(0xc820096a00)
15:09:55    /opt/go/src/github.com/couchbaselabs/sgload/sgload/reader.go:101 +0x69f
15:09:55 created by github.com/couchbaselabs/sgload/sgload.GateLoadRunner.startReaders
15:09:55    /opt/go/src/github.com/couchbaselabs/sgload/sgload/gateload_runner.go:232 +0x226
15:09:55 
```

I'm trying to run `tcpdump` packet captures to see what is happening, but a lot of packets are being dropped by the kernel, which might be skewing things making it hard to analyze the packet capture (I'm seeing stuff in wireshark that makes no sense to me..)

```
# tcpdump -s0 -w /tmp/sg2.pcap port 4984 or port 4985
tcpdump: listening on eth0, link-type EN10MB (Ethernet), capture size 65535 bytes
^C223369 packets captured
238486 packets received by filter
15117 packets dropped by kernel
```

Going to try to add some delay to the writers which will hopefully allow capture with no packet loss.

**Comment by tleyden** [comment]
This is fixed now.  I think it was config related .. the jenkins job wasn't provisioning with the correct config.

http://s61103cnt72.sc.couchbase.com:3000/dashboard/db/sync-gateway-perf-test?var-perftestrundbs=jenkins-sync-gateway-perf-test-85&from=1476806711413&to=1476813911413
