### ISSUE TITLE
sgload panic len(uniqueDocIds) != len(docs)

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/sgload#21]
To reproduce:

```
[root@s61904cnt72 ~]# sgload gateload --createreaders --createwriters --numreaders 100 --numwriters 100 --numupdaters 100 --numrevsperdoc 100 --numdocs 100000 --numchannels 100 --batchsize 100 --statsdendpoint localhost:8125 --statsdenabled --sg-url http://s61705cnt72.sc.couchbase.com:4984/db/
```

from http://uberjenkins.sc.couchbase.com/view/Performance/job/sync-gateway-perf-test/97/consoleFull

```
INFO[11-16|16:32:06] Reader pulled more docs                  reader=reader-user-14-0ad89849-9d50-4b23-91cd-304139d2f7e4 pulled=5 totalpulled=316 expecteddocs=1000 numRevGenerationsExpected=101
INFO[11-16|16:32:07] Reader pulled more docs                  reader=reader-user-49-0ad89849-9d50-4b23-91cd-304139d2f7e4 pulled=4 totalpulled=316 expecteddocs=1000 numRevGenerationsExpected=101
INFO[11-16|16:32:07] Reader pulled more docs                  reader=reader-user-50-0ad89849-9d50-4b23-91cd-304139d2f7e4 pulled=7 totalpulled=324 expecteddocs=1000 numRevGenerationsExpected=101
EROR[11-16|16:32:07] len(uniqueDocIds) != len(docs)           len(uniqueDocIds)=4 len(docs)=5
EROR[11-16|16:32:07] uniqueDocIds                             docId=16933-0ad89849-9d50-4b23-91cd-304139d2f7e4 docRevPair="{Id:16933-0ad89849-9d50-4b23-91cd-304139d2f7e4 Revision:28-eb8fdae4c1f85753a9221cb81a931f9e Error: Reason:}"
EROR[11-16|16:32:07] uniqueDocIds                             docId= docRevPair="{Id: Revision: Error: Reason:}"
EROR[11-16|16:32:07] uniqueDocIds                             docId=10133-0ad89849-9d50-4b23-91cd-304139d2f7e4 docRevPair="{Id:10133-0ad89849-9d50-4b23-91cd-304139d2f7e4 Revision:88-85abf7dd8737aa5bd1eec59f1e1f1b0c Error: Reason:}"
EROR[11-16|16:32:07] uniqueDocIds                             docId=7033-0ad89849-9d50-4b23-91cd-304139d2f7e4 docRevPair="{Id:7033-0ad89849-9d50-4b23-91cd-304139d2f7e4 Revision:80-e2bfb6c9bbab1d79540b135dad2687e8 Error: Reason:}"
EROR[11-16|16:32:07] docs                                     doc="{Id:16933-0ad89849-9d50-4b23-91cd-304139d2f7e4 Revision:28-eb8fdae4c1f85753a9221cb81a931f9e Error: Reason:}" doc.id=16933-0ad89849-9d50-4b23-91cd-304139d2f7e4 doc.rev=28-eb8fdae4c1f85753a9221cb81a931f9e
EROR[11-16|16:32:07] docs                                     doc="{Id: Revision: Error: Reason:}" doc.id= doc.rev=
EROR[11-16|16:32:07] docs                                     doc="{Id:10133-0ad89849-9d50-4b23-91cd-304139d2f7e4 Revision:88-85abf7dd8737aa5bd1eec59f1e1f1b0c Error: Reason:}" doc.id=10133-0ad89849-9d50-4b23-91cd-304139d2f7e4 doc.rev=88-85abf7dd8737aa5bd1eec59f1e1f1b0c
EROR[11-16|16:32:07] docs                                     doc="{Id: Revision: Error: Reason:}" doc.id= doc.rev=
EROR[11-16|16:32:07] docs                                     doc="{Id:7033-0ad89849-9d50-4b23-91cd-304139d2f7e4 Revision:80-e2bfb6c9bbab1d79540b135dad2687e8 Error: Reason:}" doc.id=7033-0ad89849-9d50-4b23-91cd-304139d2f7e4 doc.rev=80-e2bfb6c9bbab1d79540b135dad2687e8
INFO[11-16|16:32:07] Reader finished                          reader=reader-user-82-0ad89849-9d50-4b23-91cd-304139d2f7e4
INFO[11-16|16:32:07] Reader finished                          agent.ID=82 numdocs=316
panic: len(uniqueDocIds) != len(docs), 4 != 5

goroutine 515 [running]:
github.com/couchbaselabs/sgload/sgload.getBulkGetRequest(0xc821f9ec00, 0x5, 0x8, 0x826340, 0xc82c09b9f0, 0x0, 0x0, 0x0, 0x826340)
	/opt/go/src/github.com/couchbaselabs/sgload/sgload/reader.go:276 +0x10b9
github.com/couchbaselabs/sgload/sgload.(*Reader).pullMoreDocs.func1(0x814560, 0x0, 0x0, 0x0, 0x0)
	/opt/go/src/github.com/couchbaselabs/sgload/sgload/reader.go:212 +0x76e
github.com/couchbaselabs/sgload/sgload.RetryLoop(0x9ae1f0, 0xc, 0xc8201a3e18, 0xc8447ac480, 0x0, 0x0, 0x0, 0x0)
	/opt/go/src/github.com/couchbaselabs/sgload/sgload/reader.go:314 +0x59
github.com/couchbaselabs/sgload/sgload.(*Reader).pullMoreDocs(0xc82008fb90, 0x7f78403d7ed8, 0xc82c906f90, 0x0, 0x0, 0x0, 0x0, 0x0)
	/opt/go/src/github.com/couchbaselabs/sgload/sgload/reader.go:231 +0xe1
github.com/couchbaselabs/sgload/sgload.(*Reader).Run(0xc82008fb90)
	/opt/go/src/github.com/couchbaselabs/sgload/sgload/reader.go:111 +0x268
created by github.com/couchbaselabs/sgload/sgload.GateLoadRunner.startReaders
	/opt/go/src/github.com/couchbaselabs/sgload/sgload/gateload_runner.go:242 +0x24c

goroutine 1 [semacquire, 17 minutes]:
sync.runtime_Semacquire(0xc82000e7cc)
	/usr/local/go/src/runtime/sema.go:43 +0x26
sync.(*WaitGroup).Wait(0xc82000e7c0)
	/usr/local/go/src/sync/waitgroup.go:126 +0xb4
github.com/couchbaselabs/sgload/sgload.GateLoadRunner.waitUntilWritersFinish(0x7fff2fd486d7, 0x2c, 0x1379, 0x100, 0x7fff2fd486af, 0xe, 0xc820067d40, 0x24, 0x64, 0x64, ...)
```

**Comment by tleyden** [comment]
Another repro:

http://uberjenkins.sc.couchbase.com/view/Performance/job/sync-gateway-perf-test/104/console

**Comment by tleyden** [comment]
Unclear if this is an sgload issue or an SG issue.

**Comment by tleyden** [comment]
No longer seeing this, closing as fixed
