### ISSUE TITLE
sgload panic dns lookup

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/sgload#22]
In http://uberjenkins.sc.couchbase.com/view/Performance/job/sync-gateway-perf-test/107/console:

```
15:04:01 
15:04:01 Exception calling execute_sgload: Detected panic: panic: Error performing update: Post http://s61705cnt72.sc.couchbase.com:4984/db/_bulk_docs: dial tcp: lookup s61705cnt72.sc.couchbase.com on 10.1.1.250:53: read udp 172.23.108.85:53134->10.1.1.250:53: read: connection refused
15:04:01 
15:04:01 Traceback (most recent call last):
15:04:01   File "testsuites/syncgateway/pERROR:root:Traceback (most recent call last):
15:04:01   File "testsuites/syncgateway/performance/run_sgload_perf_test.py", line 74, in execute_sgload
15:04:01     stream_output(stderr, sys.stderr, abort_if_panic=True)
15:04:01   File "testsuites/syncgateway/performance/run_sgload_perf_test.py", line 92, in stream_output
15:04:01     raise Exception("Detected panic: {}".format(line))
15:04:01 Exception: Detected panic: panic: Error performing update: Post http://s61705cnt72.sc.couchbase.com:4984/db/_bulk_docs: dial tcp: lookup s61705cnt72.sc.couchbase.com on 10.1.1.250:53: read udp 172.23.108.85:53134->10.1.1.250:53: read: connection refused
15:04:01 
15:04:01 
15:04:01 erformance/run_sgload_perf_test.py", line 74, in execute_sgload
15:04:01     stream_output(stderr, sys.stderr, abort_if_panic=True)
15:04:01   File "testsuites/syncgateway/performance/run_sgload_perf_test.py", line 92, in stream_output
15:04:01     raise Exception("Detected panic: {}".format(line))
15:04:01 Exception: Detected panic: panic: Error performing update: Post http://s61705cnt72.sc.couchbase.com:4984/db/_bulk_docs: dial tcp: lookup s61705cnt72.sc.couchbase.com on 10.1.1.250:53: read udp 172.23.108.85:53134->10.1.1.250:53: read: connection refused
15:04:01 
15:04:01 
15:04:01 Traceback (most recent call last):
15:04:01   File "testsuites/syncgateway/performance/run_sgload_perf_test.py", line 156, in <module>
15:04:01     sg_host_main
15:04:01   File "testsuites/syncgateway/performance/run_sgload_perf_test.py", line 41, in run_sgload_on_single_loadgenerator
15:04:01     execute_sgload(lg_host, sgload_arg_list, sg_host)
15:04:01   File "testsuites/syncgateway/performance/run_sgload_perf_test.py", line 84, in execute_sgload
15:04:01     raise e
15:04:01 Exception: Detected panic: panic: Error performing update: Post http://s61705cnt72.sc.couchbase.com:4984/db/_bulk_docs: dial tcp: lookup s61705cnt72.sc.couchbase.com on 10.1.1.250:53: read udp 172.23.108.85:53134->10.1.1.250:53: read: connection refused
15:04:01 
```

**Comment by tleyden** [comment]
I believe it's a duplicate #15
