### ISSUE TITLE
RetryLoop for pullMoreDocs giving up after 8 attempts

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/sgload#30]
To reproduce:

* Run feature/issue_3_transient_errors branch
* 
```
go run main.go gateload --createwriters --numwriters 1 --createreaders --numreaders 1 --numupdaters 1 --numdocs 5 --numchannels 1 --sg-url http://192.168.11.24:4984/db/ --batchsize 2 --loglevel info --numrevsperdoc 5
```
* Run Sync Gateway commit https://github.com/couchbase/sync_gateway/commit/18eacc13d3afe645c93cffc382919936d4ea22a4  with config

```
{
  "adminInterface": ":4985",
  "log":[
    "*"
  ],
  "databases":{
    "db":{
	"server":"http://localhost:8091",
	      "bucket":"db",
      "users":{
        "GUEST":{
          "disabled":true,
          "admin_channels":[
            "*"
          ]
        },
	  "foo": {
	      "disabled":false,
	      "admin_channels": [
		  "*"
	      ],
	      "password": "bar"
	  }
      },
      "allow_empty_password":true
    }
  }
}

```

Getting error:

```
INFO[11-23|11:55:17] Updater pushed changes                   updater=writer-user-0-21561eb3-dcb9-45bf-8588-3bc5b8725300 numdocs=1
INFO[11-23|11:55:18] Updater pushed changes                   updater=writer-user-0-21561eb3-dcb9-45bf-8588-3bc5b8725300 numdocs=1
INFO[11-23|11:55:19] Updater pushed changes                   updater=writer-user-0-21561eb3-dcb9-45bf-8588-3bc5b8725300 numdocs=1
INFO[11-23|11:55:20] Updater pushed changes                   updater=writer-user-0-21561eb3-dcb9-45bf-8588-3bc5b8725300 numdocs=1
INFO[11-23|11:55:21] Updater finished                         agent.ID=0 numdocs=5
EROR[11-23|11:56:14] Error calling pullMoreDocs               agent.ID=0 since=365 err="RetryLoop for pullMoreDocs giving up after 8 attempts"
INFO[11-23|11:56:14] Reader finished                          reader=reader-user-0-21561eb3-dcb9-45bf-8588-3bc5b8725300
INFO[11-23|11:56:14] Reader finished                          agent.ID=0 numdocs=5
panic: Error calling pullMoreDoc: RetryLoop for pullMoreDocs giving up after 8 attempts

goroutine 7 [running]:
panic(0x40b360, 0xc420149d30)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/couchbaselabs/sgload/sgload.(*Reader).Run(0xc420107c30)
	/Users/tleyden/Development/gocode/src/github.com/couchbaselabs/sgload/sgload/reader.go:119 +0xc82
created by github.com/couchbaselabs/sgload/sgload.GateLoadRunner.startReaders
	/Users/tleyden/Development/gocode/src/github.com/couchbaselabs/sgload/sgload/gateload_runner.go:249 +0xff
exit status 2
```

**Comment by tleyden** [comment]
It seems that sync gateway has gotten into a broken state.  I can reproduce the issue over and over on the same running sg instance.

I started up another sync gateway on the same machine:

- Points to different couchbase server bucket (db2)
- Same SG version
- Same config, except database name is db2 and points to the db2 bucket

and cannot reproduce the issue.

Here are the logs against the working sg instance:

https://gist.github.com/tleyden/c1a864792096d85283248361574736cd

and against the broken sg instance:

https://gist.github.com/tleyden/4cfb8383e43790a97253194f4b80fbc5

**Comment by tleyden** [comment]
Looked into this w/ @adamcfraser and it turns out that it was caused by flushing the bucket which lost the Couchbase Server tap feed.

Will file a ticket to see if that is supposed to cause the db to go into the offline state.
