### ISSUE TITLE
Getting panic due to 503 error

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/sgload#42]
When running:

```
./sgload writeload --createwriters --numwriters 100 --numdocs 1000000 --numchannels 10 --batchsize 100 --statsdendpoint localhost:8125 --statsdenabled --expvarprogressenabled --loglevel debug --sg-url http://s61705cnt72.sc.couchbase.com:4984/db/
```

Sporadically seeing:

```
panic: Error creating docs in datastore.  Docs: [map[_id:752276-c4d2b958-a0d6-43cc-b3a1-afc5dd3ea34c docNum:752276 bodysize:1024 created_at:2016-12-15T17:10:27.865642064-08:00 channels:[6-c4d2b958-a0d6-43cc-b3a1-afc5dd3ea34c] body:map[field_5:aa
...

goroutine 67 [running]:
panic(0x80c4a0, 0xc49cda6830)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/couchbaselabs/sgload/sgload.(*Writer).Run(0xc420176fa0)
	/opt/go/src/github.com/couchbaselabs/sgload/sgload/writer.go:64 +0xa00
created by github.com/couchbaselabs/sgload/sgload.WriteLoadRunner.Run
	/opt/go/src/github.com/couchbaselabs/sgload/sgload/writeload_runner.go:65 +0x2b3
```

And not seeing any retry logs from http retry client.  Not sure if it's even retrying, or if it's retrying but timing out.

**Comment by tleyden** [comment]
Ok I found the issue:

```
	decoder := json.NewDecoder(resp.Body)
	if err = decoder.Decode(&bulkDocsResponse); err != nil {
		return bulkDocsResponse, err
	}

	// If any of the bulk docs had errors, return an error
	for _, docRevisionPair := range bulkDocsResponse {
		if docRevisionPair.Error != "" {
			return bulkDocsResponse, fmt.Errorf("%v", docRevisionPair.Error)
		}
	}
```

If a single doc in the bulk docs fails, then we throw an error .. and this is outside the scope of the http retry client, which is why it wasn't fixed by https://github.com/couchbaselabs/sgload/issues/3

**Comment by tleyden** [comment]
Looks like there might be a deeper problem .. the retries don't seem to be helping:

```
WARN[12-15|19:24:14] HttpClientRetry                          url=http://s61705cnt72.sc.couchbase.com:4984/db/_bulk_docs numAttempts=8
WARN[12-15|19:24:14] HttpClientRetry                          url=http://s61705cnt72.sc.couchbase.com:4984/db/_bulk_docs numAttempts=8
WARN[12-15|19:24:14] HttpClientRetry                          url=http://s61705cnt72.sc.couchbase.com:4984/db/_bulk_docs numAttempts=8
WARN[12-15|19:24:14] HttpClientRetry                          url=http://s61705cnt72.sc.couchbase.com:4984/db/_bulk_docs numAttempts=8
WARN[12-15|19:24:14] HttpClientRetry                          url=http://s61705cnt72.sc.couchbase.com:4984/db/_bulk_docs numAttempts=8
WARN[12-15|19:24:14] HttpClientRetry                          url=http://s61705cnt72.sc.couchbase.com:4984/db/_bulk_docs numAttempts=8
WARN[12-15|19:24:14] HttpClientRetry                          url=http://s61705cnt72.sc.couchbase.com:4984/db/_bulk_docs numAttempts=8
WARN[12-15|19:24:14] HttpClientRetry                          url=http://s61705cnt72.sc.couchbase.com:4984/db/_bulk_docs numAttempts=8
WARN[12-15|19:24:14] HttpClientRetry                          url=http://s61705cnt72.sc.couchbase.com:4984/db/_bulk_docs numAttempts=8
WARN[12-15|19:24:14] HttpClientRetry                          url=http://s61705cnt72.sc.couchbase.com:4984/db/_bulk_docs numAttempts=8
WARN[12-15|19:24:14] HttpClientRetry                          url=http://s61705cnt72.sc.couchbase.com:4984/db/_bulk_docs numAttempts=8
WARN[12-15|19:24:14] HttpClientRetry                          url=http://s61705cnt72.sc.couchbase.com:4984/db/_bulk_docs numAttempts=8
WARN[12-15|19:24:14] HttpClientRetry                          url=http://s61705cnt72.sc.couchbase.com:4984/db/_bulk_docs numAttempts=8
```

**Comment by tleyden** [comment]
But at least it's clear that it's retrying.  It finally failed with:

```
aaaaaaaaaaaa] _id:504615-339f1dcc-c294-4ebd-8b74-c2f8d634b27d]], Err: POST http://s61705cnt72.sc.couchbase.com:4984/db/_bulk_docs giving up after 11 attempts
```

**Comment by tleyden** [comment]
Spun off of https://github.com/couchbaselabs/sgload/issues/28
