### ISSUE TITLE
One-channel per user scenario

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/sgload#52]
TODO:

sanity check that sgload handles a large number of channels relative to the number of docs

**Comment by tleyden** [comment]
After reducing the memory usage by streaming docs, the readers no longer work in certain configs:

```
go run main.go gateload     --createreaders     --createwriters     --numwriters 10     --numupdaters 0     --numreaders 10     --numdocs 100 --batchsize 1 --numchannels 10  --loglevel debug
```

gives error:

```
DBUG[12-21|14:43:47] Feeding docs to writer                   writer=writer-user-9-121acb7e-f8a6-40dc-b5e0-d28d30fb917f
panic: Num chans (10) must be LTE to num docs (1)

goroutine 49 [running]:
panic(0x40a5c0, 0xc4201d8380)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/couchbaselabs/sgload/sgload.assignDocsToChannels(0xc42006f900, 0xa, 0x10, 0xc420224048, 0x1, 0x1, 0x24, 0xc420224048, 0x1)
	/Users/tleyden/Development/gocode/src/github.com/couchbaselabs/sgload/sgload/doc_feeder.go:21 +0x4ef
```

**Comment by tleyden** [comment]
Another case where channel distribution is uneven:

```
go run main.go gateload     --createreaders     --createwriters     --numwriters 10     --numupdaters 0     --numreaders 10     --numdocs 100 --batchsize 10 --numchannels 3  --loglevel debug
```

gives

```

panic: Reader was only expected to pull 33 docs, but pulled 36.

goroutine 18 [running]:
panic(0x40a500, 0xc420163e50)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/couchbaselabs/sgload/sgload.(*Reader).isFinished(0xc420106f20, 0xc420252000, 0x17)
	/Users/tleyden/Development/gocode/src/github.com/couchbaselabs/sgload/sgload/reader.go:159 +0x871
```
